- name: Ensure Packer is installed
  ansible.builtin.command: packer --version
  register: packer_check
  changed_when: false
  failed_when: packer_check.rc != 0

- name: Run Packer build for Debian 12
  ansible.builtin.command:
    cmd: >
      packer build
      -var "vsphere_password={{ vsphere_password }}"
      templates/packer/debian12.json.j2
  args:
    chdir: "{{ role_path }}"
  environment:
    PACKER_LOG: 1
  tags: [packerbuild]

- name: Run Packer build for Debian 13
  ansible.builtin.command:
    cmd: >
      packer build
      -var "vsphere_password={{ vsphere_password }}"
      templates/packer/debian13.json.j2
  args:
    chdir: "{{ role_path }}"
  environment:
    PACKER_LOG: 1
  tags: [packerbuild]

- name: Run Packer build for Ubuntu 22.04
  ansible.builtin.command:
    cmd: >
      packer build
      -var "vsphere_password={{ vsphere_password }}"
      templates/packer/ubuntu22.json.j2
  args:
    chdir: "{{ role_path }}"
  environment:
    PACKER_LOG: 1
  tags: [packerbuild]

- name: Run Packer build for Ubuntu 24.04
  ansible.builtin.command:
    cmd: >
      packer build
      -var "vsphere_password={{ vsphere_password }}"
      templates/packer/ubuntu24.json.j2
  args:
    chdir: "{{ role_path }}"
  environment:
    PACKER_LOG: 1
  tags: [packerbuild]

