- name: Create packer-offline-keys dir
  file:
    path: "{{ packer_offline_keys_dir }}"
    state: directory
    mode: '0700'

- name: Generate offline SSH keypair if missing
  community.crypto.openssh_keypair:
    path: "{{ packer_offline_keys_dir }}/id_ed25519"
    type: ed25519
    comment: "packer-offline-key"
    state: present
    mode: '0600'

